In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv(r'C:\AHAMMED\BIA_DATA_SCIENCE\Data_Visulization\Dataset\amazon_prime_titles.csv')

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [4]:
df.shape

(9668, 12)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   str
 1   type          9668 non-null   str
 2   title         9668 non-null   str
 3   director      7585 non-null   str
 4   cast          8435 non-null   str
 5   country       672 non-null    str
 6   date_added    155 non-null    str
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   str
 9   duration      9668 non-null   str
 10  listed_in     9668 non-null   str
 11  description   9668 non-null   str
dtypes: int64(1), str(11)
memory usage: 906.5 KB

In [6]:
df.describe(include="all")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
count,9668,9668,9668,7585,8435,672,155,9668.000000,9331,9668,9668,9668
unique,9668,2,9668,5773,7927,86,84,NaN,24,219,518,9414
top,s1,Movie,The Grand Seduction,Mark Knight,Maggie Binkley,United States,"March 30, 2021",NaN,13+,1 Season,Drama,"Arpo was designed as a commando robot, built a..."
freq,1,7814,1,113,56,253,14,NaN,2117,1342,986,15
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.341849,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.922482,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1920.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN

In [7]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2083
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.dtypes

show_id           str
type              str
title             str
director          str
cast              str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
description       str
dtype: object

In [10]:
df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)

In [11]:
for col in ['type','rating','country']:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

type
type
Movie      7814
TV Show    1854
Name: count, dtype: int64

rating
rating
13+         2117
16+         1547
ALL         1268
18+         1243
R           1010
PG-13        393
7+           385
NaN          337
PG           253
NR           223
TV-14        208
TV-PG        169
TV-NR        105
G             93
TV-G          81
TV-MA         77
TV-Y          74
TV-Y7         39
UNRATED       33
NC-17          3
AGES_18_       3
NOT_RATE       3
AGES_16_       2
16             1
ALL_AGES       1
Name: count, dtype: int64

country
country
NaN                                                         8996
United States                                                253
India                                                        229
United Kingdom                                                28
Canada                                                        16
                                                            ...
United States, Mexico                                          1
United States, Germany, Japan, United Kingdom, Hong Kong       1
Italy, Canada                                                  1
France, Belgium                                                1
Italy, Spain                                                   1
Name: count, Length: 87, dtype: int64

In [12]:
df[df["director"].isnull()].head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
17,s18,TV Show,Zoo Babies,NaN,Narrator - Gillian Barlett,NaN,NaN,2008,ALL,1 Season,"Kids, Special Interest",A heart warming and inspiring series that welc...
18,s19,TV Show,Zoë Coombs Marr: Bossy Bottom,NaN,Zoë Coombs Marr,NaN,NaN,2020,18+,1 Season,"Comedy, Talk Show and Variety",Zoë Coombs Marr has been on hiatus. Sort of. F...
20,s21,TV Show,Zoboomafoo,NaN,NaN,NaN,NaN,2001,TV-Y,1 Season,Kids,Chris and Martin Kratt bring their enthusiasm ...
21,s22,TV Show,Zo Zo Zombie: Mini-Series,NaN,"Alex Cazares, Ben Diskin, Cristina Vee, Erika ...",NaN,NaN,2020,TV-Y7,1 Season,"Action, Anime, Comedy","Zo Zo Zombie is our undead hero who, with his ..."
23,s24,TV Show,ZeroZeroZero,NaN,"ANDREA RISEBOROUGH, HAROLD TORRES, CLAUDIA PIN...",Italy,NaN,2020,18+,1 Season,TV Shows,ZeroZeroZero series follows the journey of a c...

In [13]:
df[df["country"].isnull()].head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
16,s17,Movie,Zoombies,Glenn Miller,"Marcus Anderson, Kaiwi Lyman, Andrew Asper",NaN,NaN,2016,13+,87 min,"Horror, Science Fiction",When a strange virus quickly spreads through a...
17,s18,TV Show,Zoo Babies,NaN,Narrator - Gillian Barlett,NaN,NaN,2008,ALL,1 Season,"Kids, Special Interest",A heart warming and inspiring series that welc...
18,s19,TV Show,Zoë Coombs Marr: Bossy Bottom,NaN,Zoë Coombs Marr,NaN,NaN,2020,18+,1 Season,"Comedy, Talk Show and Variety",Zoë Coombs Marr has been on hiatus. Sort of. F...
19,s20,Movie,Zoe,Drake Doremus,"Ewan McGregor, Léa Seydoux, Theo James, Mirand...",NaN,NaN,2018,R,104 min,Science Fiction,ZOE tells a tale of forbidden love between an ...
20,s21,TV Show,Zoboomafoo,NaN,NaN,NaN,NaN,2001,TV-Y,1 Season,Kids,Chris and Martin Kratt bring their enthusiasm ...

In [14]:
df[df["date_added"].isnull()].head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
16,s17,Movie,Zoombies,Glenn Miller,"Marcus Anderson, Kaiwi Lyman, Andrew Asper",NaN,NaN,2016,13+,87 min,"Horror, Science Fiction",When a strange virus quickly spreads through a...
17,s18,TV Show,Zoo Babies,NaN,Narrator - Gillian Barlett,NaN,NaN,2008,ALL,1 Season,"Kids, Special Interest",A heart warming and inspiring series that welc...
18,s19,TV Show,Zoë Coombs Marr: Bossy Bottom,NaN,Zoë Coombs Marr,NaN,NaN,2020,18+,1 Season,"Comedy, Talk Show and Variety",Zoë Coombs Marr has been on hiatus. Sort of. F...
19,s20,Movie,Zoe,Drake Doremus,"Ewan McGregor, Léa Seydoux, Theo James, Mirand...",NaN,NaN,2018,R,104 min,Science Fiction,ZOE tells a tale of forbidden love between an ...
20,s21,TV Show,Zoboomafoo,NaN,NaN,NaN,NaN,2001,TV-Y,1 Season,Kids,Chris and Martin Kratt bring their enthusiasm ...

In [15]:
df = df.drop(columns=["country", "date_added"])

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   str
 1   type          9668 non-null   str
 2   title         9668 non-null   str
 3   director      7585 non-null   str
 4   cast          8435 non-null   str
 5   release_year  9668 non-null   int64
 6   rating        9331 non-null   str
 7   duration      9668 non-null   str
 8   listed_in     9668 non-null   str
 9   description   9668 non-null   str
dtypes: int64(1), str(9)
memory usage: 755.4 KB

In [17]:
df["director"] = df["director"].fillna("Unknown")
df["cast"] = df["cast"].fillna("Unknown")
df["rating"] = df["rating"].fillna("Not Rated")

In [18]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [19]:
df["title"].duplicated().sum()

np.int64(0)

In [20]:
df[df["title"].duplicated(keep=False)].sort_values("title")

Empty DataFrame
Columns: [show_id, type, title, director, cast, release_year, rating, duration, listed_in, description]
Index: []

In [21]:
df[["duration_value", "duration_unit"]] = df["duration"].str.extract(r"(\d+)\s+(\w+)")

df["duration_value"] = df["duration_value"].astype(int)

In [22]:
df[["duration", "duration_value", "duration_unit"]].head(10)

  duration  duration_value duration_unit
0  113 min             113           min
1  110 min             110           min
2   74 min              74           min
3   69 min              69           min
4   45 min              45           min
5   52 min              52           min
6   98 min              98           min
7  131 min             131           min
8   87 min              87           min
9   92 min              92           min

In [23]:
df["type"].value_counts()

type
Movie      7814
TV Show    1854
Name: count, dtype: int64

In [24]:
df["rating"].value_counts()

rating
13+          2117
16+          1547
ALL          1268
18+          1243
R            1010
PG-13         393
7+            385
Not Rated     337
PG            253
NR            223
TV-14         208
TV-PG         169
TV-NR         105
G              93
TV-G           81
TV-MA          77
TV-Y           74
TV-Y7          39
UNRATED        33
NC-17           3
AGES_18_        3
NOT_RATE        3
AGES_16_        2
16              1
ALL_AGES        1
Name: count, dtype: int64

In [25]:
df["duration_unit"].value_counts()

duration_unit
min        7814
Season     1342
Seasons     512
Name: count, dtype: int64

In [26]:
df["duration_unit"] = df["duration_unit"].replace({
    "Season": "Seasons"
})

In [27]:
df["duration_unit"].value_counts()

duration_unit
min        7814
Seasons    1854
Name: count, dtype: int64

In [28]:
df["rating"] = df["rating"].replace({
    "UNRATED": "Not Rated",
    "NOT_RATE": "Not Rated",
    "ALL_AGES": "ALL",
    "AGES_16_": "16+",
    "AGES_18_": "18+",
    "16": "16+"
})

In [29]:
df["rating"].value_counts()

rating
13+          2117
16+          1550
ALL          1269
18+          1246
R            1010
PG-13         393
7+            385
Not Rated     373
PG            253
NR            223
TV-14         208
TV-PG         169
TV-NR         105
G              93
TV-G           81
TV-MA          77
TV-Y           74
TV-Y7          39
NC-17           3
Name: count, dtype: int64

In [30]:
df["release_decade"] = (df["release_year"] // 10) * 10

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         9668 non-null   str
 1   type            9668 non-null   str
 2   title           9668 non-null   str
 3   director        9668 non-null   str
 4   cast            9668 non-null   str
 5   release_year    9668 non-null   int64
 6   rating          9668 non-null   str
 7   duration        9668 non-null   str
 8   listed_in       9668 non-null   str
 9   description     9668 non-null   str
 10  duration_value  9668 non-null   int64
 11  duration_unit   9668 non-null   str
 12  release_decade  9668 non-null   int64
dtypes: int64(3), str(10)
memory usage: 982.0 KB

In [32]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast              0
release_year      0
rating            0
duration          0
listed_in         0
description       0
duration_value    0
duration_unit     0
release_decade    0
dtype: int64

In [33]:
df.describe(include="all")

,show_id,type,title,director,cast,release_year,rating,duration,listed_in,description,duration_value,duration_unit,release_decade
count,9668,9668,9668,9668,9668,9668.000000,9668,9668,9668,9668,9668.000000,9668,9668.000000
unique,9668,2,9668,5774,7928,NaN,19,219,518,9414,NaN,2,NaN
top,s1,Movie,The Grand Seduction,Unknown,Unknown,NaN,13+,1 Season,Drama,"Arpo was designed as a commando robot, built a...",NaN,min,NaN
freq,1,7814,1,2083,1233,NaN,2117,1342,986,15,NaN,7814,NaN
mean,NaN,NaN,NaN,NaN,NaN,2008.341849,NaN,NaN,NaN,NaN,74.131775,NaN,2004.064957
std,NaN,NaN,NaN,NaN,NaN,18.922482,NaN,NaN,NaN,NaN,50.591673,NaN,19.396201
min,NaN,NaN,NaN,NaN,NaN,1920.000000,NaN,NaN,NaN,NaN,0.000000,NaN,1920.000000
25%,NaN,NaN,NaN,NaN,NaN,2007.000000,NaN,NaN,NaN,NaN,41.000000,NaN,2000.000000
50%,NaN,NaN,NaN,NaN,NaN,2016.000000,NaN,NaN,NaN,NaN,86.000000,NaN,2010.000000
75%,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,101.000000,NaN,2010.000000
max,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN,601.000000,NaN,2020.000000

In [34]:
sorted(df["rating"].unique())

['13+',
 '16+',
 '18+',
 '7+',
 'ALL',
 'G',
 'NC-17',
 'NR',
 'Not Rated',
 'PG',
 'PG-13',
 'R',
 'TV-14',
 'TV-G',
 'TV-MA',
 'TV-NR',
 'TV-PG',
 'TV-Y',
 'TV-Y7']

In [35]:
df.drop(columns=["duration"], inplace=True)

In [36]:
df["primary_genre"] = df["listed_in"].str.split(",").str[0].str.strip()

In [37]:
def duration_category(x):
    if x < 60:
        return "Short"
    elif x <= 120:
        return "Medium"
    else:
        return "Long"

df["duration_category"] = df["duration_value"].apply(duration_category)

In [38]:
df.info()
df.describe(include="all")
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   show_id            9668 non-null   str
 1   type               9668 non-null   str
 2   title              9668 non-null   str
 3   director           9668 non-null   str
 4   cast               9668 non-null   str
 5   release_year       9668 non-null   int64
 6   rating             9668 non-null   str
 7   listed_in          9668 non-null   str
 8   description        9668 non-null   str
 9   duration_value     9668 non-null   int64
 10  duration_unit      9668 non-null   str
 11  release_decade     9668 non-null   int64
 12  primary_genre      9668 non-null   object
 13  duration_category  9668 non-null   str
dtypes: int64(3), object(1), str(10)
memory usage: 1.0+ MB

show_id              0
type                 0
title                0
director             0
cast                 0
release_year         0
rating               0
listed_in            0
description          0
duration_value       0
duration_unit        0
release_decade       0
primary_genre        0
duration_category    0
dtype: int64

In [39]:
# Check unique values
print(df["type"].unique())
print(df["duration_unit"].unique())
print(sorted(df["rating"].unique()))

# Check duplicates again
print(df.duplicated().sum())

# Check missing values
print(df.isnull().sum().sum())

<StringArray>
['Movie', 'TV Show']
Length: 2, dtype: str
<StringArray>
['min', 'Seasons']
Length: 2, dtype: str
['13+', '16+', '18+', '7+', 'ALL', 'G', 'NC-17', 'NR', 'Not Rated', 'PG', 'PG-13', 'R', 'TV-14', 'TV-G', 'TV-MA', 'TV-NR', 'TV-PG', 'TV-Y', 'TV-Y7']
0
0

In [40]:
df.to_csv("amazon_prime_titles_cleaned.csv", index=False)

In [41]:
df[df["description"].str.contains("Copyright: TV TOKYO", na=False)]

,show_id,type,title,director,cast,release_year,rating,listed_in,description,duration_value,duration_unit,release_decade,primary_genre,duration_category
699,s700,TV Show,The Dancing Detective Dekadance,Unknown,Unknown,2016,13+,TV Shows,Dekadance is an undercover idol group. Their a...,1,Seasons,2010,TV Shows,Short
1005,s1006,TV Show,Silver and Gold,Unknown,Unknown,2017,TV-NR,TV Shows,"Tetsuo Morita (Sosuke Ikematsu), a good-for-no...",1,Seasons,2010,TV Shows,Short

In [42]:
df[df["description"].str.contains("BANANA FISH", na=False)]

,show_id,type,title,director,cast,release_year,rating,listed_in,description,duration_value,duration_unit,release_decade,primary_genre,duration_category
3159,s3160,TV Show,BANANA FISH,Unknown,"Ash Lynx: Yuma Uchida, Okumura Eiji: Kenji Noj...",2018,TV-NR,TV Shows,"Ash Lynx, a 17-year-old boy, is the boss of a ...",1,Seasons,2010,TV Shows,Short

In [43]:
row = df[df["description"].str.contains("Copyright: TV TOKYO", na=False)].iloc[0]

print(repr(row["description"]))

'Dekadance is an undercover idol group. Their assignment is to solve crimes in the show biz world. Tatsuya is thrown into the group together with a former con artist, former child star, unsocial netizen and an empty-headed part timer. Though at first the members do not get along, each time a case is solved, the group gains popularity and rises to stardom.\nCopyright: TV TOKYO'

In [44]:
row = df[df["description"].str.contains("BANANA FISH", na=False)].iloc[0]

print(repr(row["description"]))

'Ash Lynx, a 17-year-old boy, is the boss of a street-kids gang in New York. One day, a man who was murdered before his eyes entrusts him with something.\nAnd the last words uttered by that dying man was the phrase, ""BANANA FISH"". That is the word his brother, Griffin, often mutters. Ash has a destined encounter with Eiji, a kind Japanese boy who comes to New York as a cameraman assistant.'

In [45]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = (
        df[col]
        .str.replace(r"\r\n|\r|\n", " ", regex=True)
        .str.strip()
    )

C:\Users\ahamm\AppData\Local\Temp\ipykernel_16028\668864643.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

In [46]:
row = df[df["show_id"] == "s700"].iloc[0]
print(repr(row["description"]))

'Dekadance is an undercover idol group. Their assignment is to solve crimes in the show biz world. Tatsuya is thrown into the group together with a former con artist, former child star, unsocial netizen and an empty-headed part timer. Though at first the members do not get along, each time a case is solved, the group gains popularity and rises to stardom. Copyright: TV TOKYO'